notifications:
  email: false
language: node_js
node_js:
  - stable
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g codecov
  - npm install -g jest-cli
script:
  - npm run build 
  - jest test --ci --colors && codecov
  - npm run security-check